# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test

on:
    push:
        branches: [master]

    # Run tests for any PRs.
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js to test
              uses: actions/setup-node@v1
              with:
                  node-version: 12
            - run: npm i
            - run: npm test
              env:
                  CI: true
